name: CI/CD Pipeline - Frontend

on:
  push:
    branches:
      - deploy

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repositorio
        uses: actions/checkout@v4

      - name: Login a Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build y Push imagen Docker
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/frontend-despacho:latest
          build-args: |
            VITE_VENTAS_URL=${{ secrets.VITE_VENTAS_URL }}
            VITE_DESPACHOS_URL=${{ secrets.VITE_DESPACHOS_URL }}

      - name: Despliegue en EC2
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_PROXY_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/frontend-despacho:latest
            docker stop frontend || true
            docker rm frontend || true
            docker run -d \
              --name frontend \
              --restart unless-stopped \
              -p 80:8080 \
              ${{ secrets.DOCKERHUB_USERNAME }}/frontend-despacho:latest
